# GitHub Actions Workflow for Great Learning Action

# Define the name of the workflow
name: Great Learning Action

# Specify events that trigger the workflow
on:
  # Run the workflow on push events to the main branch
  push:
    branches: [main]
  # Run the workflow on pull request events targeting the main branch
  pull_request:
    branches: [$default-branch] # Note: Check if this branch reference is intended, might need correction

# Define the jobs to be executed in the workflow
jobs:
  # Define a job named 'build' that runs on an Ubuntu environment
  build:
    runs-on: ubuntu-latest

    # Specify the steps to be executed in the job
    steps:
      # Step 1: Set up Python with version 3.9
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Step 2: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Install Python dependencies from the requirements.txt file
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build and push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: pramit16/img2
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


